# Generated by Django 4.0.1 on 2022-03-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mart_python', '0003_product_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('customerId', models.IntegerField()),
                ('productName', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobileNo',
            field=models.BigIntegerField(),
        ),
    ]
