# Generated by Django 4.0.1 on 2022-03-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mart_python', '0006_cart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
